apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
type: Opaque
stringData:
  ZONE: "kuberbitnetes.xyz"
  PROXIED: "false"
  API_KEY: "Lc5XagGvHZ1a3DXn33DjUmKi7g5iZnP6iLuS2mUR"
  SUBDOMAIN: vpn