apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-benchmark
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: wrk
        image: markmckessock/wrk
        command: ["wrk",  "-t4", "-c20", "-d30s", "http://wikijs.default.svc:3000/healthz"]
      restartPolicy: Never
