apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-benchmark
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: wrk
        image: markmckessock/wrk
        command: ["wrk",  "-t12", "-c400", "-d30s", "http://wikijs.default.svc/healthz"]
      restartPolicy: Never
