apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 5m
  path: "./helm_repositories"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/traefik-mesh/install/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---