---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cloudflare-tunnel/ks.yaml
  - ./wireguard-client/ks.yaml
  # - ./cloudflare-ddns/ks.yaml
  
