---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations: 
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: default
    
