apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-waf
data:
  whoami.conf: |
    # Nginx configuration for both HTTP and SSL

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80 default_server;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;
        set $upstream http://whoami.whoami.svc:80;
        set $always_redirect off;

        location / {
            client_max_body_size 0;

            if ($always_redirect = on) {
                return 301 https://$host$request_uri;
            }

            include includes/proxy_backend.conf;

            index index.html index.htm;
            root /usr/share/nginx/html;
        }

        include includes/location_common.conf;

    }
