apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: vyos-testing
  namespace: nsm-system
spec:
  payload: ETHERNET
  matches:
    - source_selector:
        app: r1
      routes:
        - destination_selector:
            app: r2
    - source_selector:
        app: r2
      routes:
        - destination_selector:
            app: r3
