apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1
  namespace: vyos-testing
spec:
  selector:
    matchLabels:
      app: r1
  template:
    metadata:
      labels:
        app: r1
      annotations:
        networkservicemesh.io: kernel://vyos-testing-2/nsm-1
    spec:
      containers:
        - name: r1
          # image: vyos/vyos-build:current
          image: ubuntu
          command: ["/bin/bash", "-c", "sleep 3600"]
          # ports:
          #   - containerPort: <Port>
