apiVersion: apps/v1
kind: Deployment
metadata:
  name: r3
  namespace: vyos-testing
spec:
  selector:
    matchLabels:
      app: r3
  template:
    metadata:
      labels:
        app: r3
      annotations:
        networkservicemesh.io: kernel://vyos-testing/nsm-1
    spec:
      containers:
        - name: r3
          # image: vyos/vyos-build:current
          image: ubuntu
          command:
            ["apt update && apt install -y iproute2 iputils-ping && sleep 3600"]
          # ports:
          #   - containerPort: <Port>
