---
tunnel: internet
credentials-file: /etc/cloudflared/creds/credentials.json
protocol: quic
metrics: 0.0.0.0:2000
no-autoupdate: false
ingress:
  - hostname: test.kuberbitnetes.xyz
    service: hello_world
  - hostname: api.kuberbitnetes.xyz
    service: tcp://kubernetes.default.svc:443
    originRequest:
      proxyType: socks
      noTLSVerify: true
  - hostname: "*.kuberbitnetes.xyz"
    service: https://ingress-nginx-controller.network.svc
    originRequest:
      noTLSVerify: true
  - service: http_status:404
