apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"bf7e9797181acf840378c71d15bdce9a","TunnelSecret":"Bi0xKoWnE2wZqFj/ZW4gQrKHTDen8NLhYt1Xbv1Zrp0=","TunnelID":"4ac02276-65e5-4672-847c-21e526306a2b"}
