---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: cloudflare/cloudflared
      tag: 2023.3.1

    service:
      main:
        enabled: false

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        enabled: true
        type: configMap
        name: cloudflared-config
        mountPath: /etc/cloudflared/config/config.yaml
        subPath: config.yaml
        readOnly: true
      tunnel-credentials:
        enabled: true
        type: secret
        name: cloudflare-tunnel-credentials
        mountPath: /etc/cloudflared/creds/credentials.json
        subPath: credentials.json
        readOnly: true

    args:
      - tunnel
      - --config
      - /etc/cloudflared/config/config.yaml
      - run

    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
