---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./helmrelease.yaml
  - ./credentials.yaml
configMapGenerator:
  - name: cloudflared-config
    files:
      - config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
