---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
spec:
  interval: 15m
  chart:
    spec:
      chart: wiki
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: requarks
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: wikijs.kuberbitnetes.xyz
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - wikijs.kuberbitnetes.xyz