apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnf-2
  namespace: sfc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnf-2
  template:
    metadata:
      labels:
        app: vnf-2
    spec:
      containers:
        - name: vnf-2
          image: containous/whoami:v1.4.0
          ports:
            - name: http
              containerPort: 80
