---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kuma
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./clusters/capstone-demo/apps/kuma/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
