apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: helm-repositories
  path: "./clusters/istio/istio"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio
  path: "./clusters/istio/istio-ingress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-example
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-ingress
  path: "./clusters/istio/bookinfo-example"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system