apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m