apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      version: 4.0.1
  interval: 1h
  values:
    controller:
      ingressClassResource:
        enabled: true
        default: true
      admissionWebhooks:
        enabled: false
