---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./coredns/ks.yaml
  - ./reloader/ks.yaml
  - ./kuma/ks.yaml
