apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: bookstack
spec:
  chart:
    spec:
      chart: bookstack
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 5.1.2
  interval: 1h
  values:
    persistence:
      config:
        enabled: true
        mountPath: /config
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
    env:
      DB_HOST: bookstack
      DB_USER: bookstack
      DB_PASS: bookstack
      DB_DATABASE: bookstack
