apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      version: 0.7.0
  interval: 1h
  values:
    lapi:
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
      dashboard:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
          ignressClassName: kong
          hosts:
            - crowdsec.kuberbitnetes.xyz
          tls:
            - secretName: crowdsec-tls
              hosts:
                - crowdsec.kuberbitnetes.xyz
    agent:
      acquisition:
        - namespace: nginx-waf
          podName: nginx-waf-*
          program: nginx
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
        - name: COLLECTIONS
          value: "crowdsecurity/nginx"
