apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nsm
  namespace: flux-system
spec:
  interval: 5m
  path: "./common/nsm/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nsm
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/vyos-testing/vyos"
  prune: true
  dependsOn:
    - name: nsm
  sourceRef:
    kind: GitRepository
    name: flux-system
