---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./clusters/capstone-demo/apps/observability/prometheus-stack/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kuma-grafana-dashboards
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./clusters/capstone-demo/apps/observability/prometheus-stack/app"
  prune: true
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

