# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: jaeger
#   namespace: observability
# spec:
#   chart:
#     spec:
#       chart: jaeger-operator
#       sourceRef:
#         kind: HelmRepository
#         name: jaegertracing
#         namespace: flux-system
#       version: 2.37.0
#   interval: 1h
#   values:
#     rbac:
#       clusterRole: true
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: 0.64.2
  interval: 1h
  values:
    allInOne:
      enabled: true
      ingress:
        ingressClassName: kong
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - jaeger.kuberbitnetes.xyz
        tls:
          - hosts:
              - jaeger.kuberbitnetes.xyz
            secretName: jaeger-tls
