apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: 2.37.0
  interval: 1h
