apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.31
    options:
      log-level: info
      query:
        base-path: /jaeger
      prometheus:
        server-url: "http://kube-prometheus-stack-prometheus:9090"
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000
