apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: kuma-system
spec:
  chart:
    spec:
      chart: kuma
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      version: 2.0.0
  interval: 1h
  values:
    controlPlane:
      tls:
        general:
          secretName: kuma-certs
          caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiRENDQWxTZ0F3SUJBZ0lRU0U4YVduV2ZSVS85eGJpVURvdkhFREFOQmdrcWhraUc5dzBCQVFzRkFEQXQKTVNzd0tRWURWUVFERXlKcmRXMWhMV052Ym5SeWIyd3RjR3hoYm1VdWEzVnRZUzF6ZVhOMFpXMHVjM1pqTUI0WApEVEl5TVRFd09ERTJNalF6TVZvWERUTXlNVEV3TlRFMk1qUXpNVm93TFRFck1Da0dBMVVFQXhNaWEzVnRZUzFqCmIyNTBjbTlzTFhCc1lXNWxMbXQxYldFdGMzbHpkR1Z0TG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFLUWRUVXhaUnVrRlg1YkpaV1JSa3RMSWltSGRiVWVLMGFBdFhyckoxRnhkTGZtOApnMEl2RXEzU2lncGZFQlRoa0I1U0dpK0VLMUFWcmdDRzJPSENqd29PbzZjU0VKeXl6eDhEc3NFNTFFNHNBNkNyCk9OOFV1N2JpajR2NHdNS0psQkh2bWs1Z0RvUXRmQndXeDhVTGlBUitrUnEzOUNVQ3JXejFWL1pWc2Q1QmtKK0wKTVBkS2MyNEtEakFHL2p6em1HSE5YSUFwRUFJRFQyTXpYclhqbFdFSVZuRzhtS2pHd3R4amxoRDJDOGlVemd3VQpkenRFM3ZteWFsa3YvSlRJVU9tMWwwa0Rib2JpOXFqcHlFUlFsVWhLNmoyeFJjcHNmd211RUlOODRoVzhVTVdOCmJxczFvL2JHK2srMG80WVZlRU43WXNDZjQ4R214QzhYWi8razJFTUNBd0VBQWFPQmh6Q0JoREFPQmdOVkhROEIKQWY4RUJBTUNBcVF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVBQmdqK2llOTVYdWFHNDArckp2Q0piYitSVTR3TFFZRFZSMFJCQ1l3SklJaWEzVnRZUzFqCmIyNTBjbTlzTFhCc1lXNWxMbXQxYldFdGMzbHpkR1Z0TG5OMll6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKSm85NVQvRTZBRzg4ZzdER1lQVkp1Z0t4bHA2amVaM3E3TVFQS2VINnM5M1VLVmJXY1ZaSVNMTmJlR0hVQ0MregpPbDRjbnhxOXZvcTQ0b0RZMUJUSDdiUE4yNUdBUDFpQXVPbDZXUUt5dWV4YlBLYkpsa1dxYVdRNGExL0Z6ZFdaCmFYYjdjeUtHNG5NeTNDNTM5S1ZGZk9ZSXI4a3ExdUx4NkthWDZ6N1NrcEdZSENYSnVzOTZ2R3l1QTZEalVNMkwKSU9wV3B1d09MUE9JcjJYUG9hVzVydXh4cHZkK2pPdFhZc2U0SW5uQ3ZaWlNSQjZKUTc3alc2aVFscS82L1QzLwpjbWhFdUllY2VycE1KRjA1YzRDelM4TXdJN3B1YUtGa1pJaVpoVnBBOWZpcXYrWXlaSVJmWldLeUpDVjVSWjZKCjlIeXM4VnhiZ3k0RTl4Qm52blZlL0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
