apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: kuma-system
spec:
  chart:
    spec:
      chart: kuma
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      version: 1.8.0
  interval: 1h
  values:
    controlPlane:
      tls:
        general:
          secretName: kuma-certs
