apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: kuma-system
spec:
  chart:
    spec:
      chart: kuma
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      version: 2.0.0
  interval: 1h
  values:
    global:
      ingress:
        enabled: true
        ingressClassName: kong
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hostname: kuma.kuberbitnetes.xyz
    controlPlane:
      tls:
        general:
          secretName: kuma-certs
          caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqVENDQW5XZ0F3SUJBZ0lSQU5PU1p6bWRrL05uWUJ2RmJOTGd6SWt3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFck1Da0dBMVVFQXhNaWEzVnRZUzFqYjI1MGNtOXNMWEJzWVc1bExtdDFiV0V0YzNsemRHVnRMbk4yWXpBZQpGdzB5TWpFeE1EZ3hOalF5TWpSYUZ3MHpNakV4TURVeE5qUXlNalJhTUMweEt6QXBCZ05WQkFNVEltdDFiV0V0ClkyOXVkSEp2YkMxd2JHRnVaUzVyZFcxaExYTjVjM1JsYlM1emRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRRGtFcVUzL0tlU1ZXRWxwdlNDakcxdHQ4UGhOZ2orazdPRktKLzlBL0xybGxrOApaTzJyOU0xc2paOHpyWTZTb2pKa1FJeEV4TDVMbHg1ckxWcVBvWCs3bFc3dFd4OStvR0NlREZzZTU1SHB3Rno1Cnd0SlMrSjNVdnVwWGovY0lhUU9ZNUJhMjFIbk9BaEpLWCtlUG9pcWh1QUNDcUtxalp6S0xoZUVIK0l3dWRRUk0KRnV1WWhTbjJwaitwMkU4dmFwZHdrV0xKZllqZWFNdE9CRUU5OU8vZnBGeVY5YWNhU2pZR0NOWkZDbWdIN0k3MwpOakd2c0Q5RGNpVjQ2NTFOVmxQOENhQmE2QUJwcEc2T0FDMUxaUUlDdkFwdDZ0UVdHVE1aWDdReCs5dUVSZHp6Ci9vZGVqVERhUUlZT204QVNYUWtNS0JDNGRKdjZzRW5yYXVKNG1zaXBBZ01CQUFHamdhY3dnYVF3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGSXdHODNESzdReDB6WlBDRE1KRWsvV3E3NlQyTUUwR0ExVWRFUVJHTUVTQ0ltdDFiV0V0ClkyOXVkSEp2YkMxd2JHRnVaUzVyZFcxaExYTjVjM1JsYlM1emRtT0NIbXQxYldFdFkyOXVkSEp2YkMxd2JHRnUKWlM1cmRXMWhMWE41YzNSbGJUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF3dGl0WnVZMzREUk5RblVGWnBpdwpTdzRKZzNUcmtHMnp3L1QzK2RnTmpVbzIxZnFwZFhzREVlOEJUczI3YW1lSElCMWk4Q0hrS3VLK0drNWNEWU94Cm90eloyM1Z1QU41Yk41c3d5MHVmRGdnMHNiUEhxY1ZmY09mZ1ZnNzE2OEJEZndvVFF5STU2ejdPRnJWN1RBWTUKd1hvM2x3dUdERE5aWmZGTmRIcitsSEFZVnEzcUZnUHdxQkNHYTZ2dXFIK2NLdFpqejZjRUR6NVhUcForZ3E2cgpJK251T3VQVkpLWkRuS2JNYm9abmZZbVR0T29BeVZXZzMrRXhwdFNUN0dWKzc2VTN5OXRRWVd2bG1MVDIvNThhCmFtZU9LaWdnVE56NHRGSm9JeG9KdmpQMVl5ek5JcEpMTUN4UWxYNm5sdWw3YW9VT0RCQUlsN2lFVXFrTGlyUmgKWUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
