apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nsm
  namespace: flux-system
spec:
  interval: 5m
  path: "./common/nsm/nsm"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
