apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      version: 0.8.48
  interval: 1h
  values:
    domain: kuberbitnetes.xyz
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kong
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      subdomain: authelia
