apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      version: 0.8.48
  interval: 1h
  values:
    domain: kuberbitnetes.xyz
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kong
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      subdomain: authelia
    configMap:
      session:
        redis:
          host: redis-master.authelia.svc
      storage:
        postgres:
          host: postgres-postgresql.authelia.svc
      notifier:
        smtp:
          enabled: false
        filesystem:
          enabled: true
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: true

    pod:
      extraVolumes:
        - name: authelia-users
          secret:
            secretName: authelia-users
            items:
              - key: users_database.yml
                path: users_database.yml
      extraVolumeMounts:
        - mountPath: /config/users_database.yml
          name: authelia-users
          subPath: users_database.yml
          readOnly: true
    secret:
      storage:
        value: authelia
