apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      mark:
        disabled: false
        displayname: "Mark Mckessock"
        password: "$argon2id$v=19$m=65536,t=3,p=4$510zFC5pZTq4J85aw8bk8A$FptBmieUCntv+Swt4U52PijS5tySV5d2Z8oLLxMv/Oo"
        email: mark.mckessock@gmail.com
        groups:
          - admin
