apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: authelia
spec:
  secretName: kuberbitnetes-wildcard
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.kuberbitnetes.xyz"
  dnsNames:
    - kuberbitnetes.xyz
    - "*.kuberbitnetes.xyz"
