apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-mesh
spec:
  chart:
    spec:
      chart: traefik-mesh
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 4.1.1
  interval: 1h
# TODO: Prometheus service monitor
