---
# Source: app-template/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    app.kubernetes.io/service: wikijs
    app.kubernetes.io/instance: wikijs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wikijs
    helm.sh/chart: app-template-1.2.1
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: wikijs
    app.kubernetes.io/name: wikijs
---
# Source: app-template/templates/common.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: default
  labels:
    app.kubernetes.io/instance: wikijs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wikijs
    helm.sh/chart: app-template-1.2.1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wikijs
      app.kubernetes.io/instance: wikijs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wikijs
        app.kubernetes.io/instance: wikijs
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nginx-waf
              weight: 100
      containers:
        - name: wikijs
          image: "ghcr.io/linuxserver/wikijs:version-2.5.201"
          imagePullPolicy:
          env:
            - name: TZ
              value: America/Toronto
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 100Mi