apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 5m
  values:
    identity:
      issuer:
        tls:
          crtPEM: |
            -----BEGIN CERTIFICATE-----
            MIIBszCCAVmgAwIBAgIRAL32v6+wgVgw/zqldSPFOvswCgYIKoZIzj0EAwIwJTEj
            MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIxMDE4MTM1
            NjE5WhcNMjMxMDE4MTM1NjE5WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJk
            LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASUFn3GrmM7
            BASFyLWaRPQo8ijZIkCti5B9SMhdDcOza1nVmgSAksUusAgyRLH6hN+zsm7jYvvu
            o6bgY8U1UdHco2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIB
            ADAdBgNVHQ4EFgQUgR7dEwszzKBQtoXLtnK4o6bGhfAwHwYDVR0jBBgwFoAUek1t
            gqHOiNkGYTQPHvt00K/9GmUwCgYIKoZIzj0EAwIDSAAwRQIhAJeBew2wE3UBW7qx
            LfCuVcUsWm/lALQyfl+QiiAZLM8NAiAXqVX3TNVaDAKgQUIGg5GZ3LMUXMCXCxpk
            AJYAZim/YQ==
            -----END CERTIFICATE-----
          keyPEM: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIDdYsz3AYxLuA0KwDRwMZDE18kcUfJ5U1B8EeXRdO60LoAoGCCqGSM49
            AwEHoUQDQgAElBZ9xq5jOwQEhci1mkT0KPIo2SJArYuQfUjIXQ3Ds2tZ1ZoEgJLF
            LrAIMkSx+oTfs7Ju42L77qOm4GPFNVHR3A==
            -----END EC PRIVATE KEY-----
    identityTrustAnchorsPEM: |
      -----BEGIN CERTIFICATE-----
      MIIBjzCCATSgAwIBAgIRAJtiv7loKFLjPcWENA6lRCowCgYIKoZIzj0EAwIwJTEj
      MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIxMDE4MTM1
      NjEwWhcNMzIxMDE1MTM1NjEwWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
      c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKhxmShZ/SGECnFj
      1xLUjOG9ylQsOUmopad5//Xto1p6GzDsnNBSj3x7YJE6FHCyvqqz7vbEYEiPDYFo
      r1BX54+jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
      A1UdDgQWBBR6TW2Coc6I2QZhNA8e+3TQr/0aZTAKBggqhkjOPQQDAgNJADBGAiEA
      1c2WNU7WubKholFwdgAwcxy8YJwb0P7QqQlCiFatHY8CIQDePcpaFvjmz0Z5ktUy
      2v8+v5h4mOy0iF3bgU2HuqM62Q==
      -----END CERTIFICATE-----
