---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kuma.io/sidecar-injection: disabled
  annotations:
    kuma.io/mesh: default
