apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: 2022.11.0
  interval: 1h
  values:
    ingress:
      enabled: true
      ingressClassName: kong
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: authentik.kuberbitnetes.xyz
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: authentik-tls
          hosts:
            - authentik.kuberbitnetes.xyz
    authentik:
      secret_key: H9mUdgp@!i59%aiYan%^YMCeNgF3BQtsXQfseWX6Ra2zHd!RXu
      postgresql:
        password: authentik
    postgresql:
      enabled: true
      postgresqlPassword: authentik
    redis:
      enabled: true
