apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  name: classifier
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
        port: http/80
  conf:
    http:
      rules:
        - matches:
            - path:
                match: PREFIX
                value: /
          backends:
            - destination:
                kuma.io/service: whoami-svc_sfc_svc_80
        - matches:
            - path:
                match: PREFIX
                value: /chain1
          backends:
            - destination:
                kuma.io/service: vnf-1-svc_sfc_svc_80
          filters:
            - requestHeader:
                set:
                  - name: Chain-Id
                    value: "1"
        - matches:
            - path:
                match: PREFIX
                value: /chain2
          backends:
            - destination:
                kuma.io/service: vnf-1-svc_sfc_svc_80
          filters:
            - requestHeader:
                set:
                  - name: Chain-Id
                    value: "2"
