apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: redirect-test
spec:
  sources:
    - match:
        kuma.io/service: vnf-1-svc_sfc_svc_80
  destinations:
    - match:
        kuma.io/service: whoami-svc_sfc_svc_80
  conf:
    http:
      - match:
          headers:
            Chain-Id:
              exact: "1"
        destination:
          kuma.io/service: vnf-2-svc_sfc_svc_80
    # destination:
    #   kuma.io/service: whoami-svc_sfc_svc_80
